### ISSUE TITLE
UI Refresh

### ISSUE THREAD

**Issue by TheoStanica** [TheoStanica/mark-manager#62]
Dashboard similar to [this](https://imgur.com/a/I1S908E)

**Comment by RaduAlbastroiu** [comment]
Badge with avatar and screen name for twitter connected on dashboard

**Comment by RaduAlbastroiu** [comment]
Login & Register on first screen -> don't have and account create one now

**Comment by RaduAlbastroiu** [comment]
Workable streams, maybe a default stream with your tweets

**Comment by RaduAlbastroiu** [comment]
Forget password screen redesign

**Comment by RaduAlbastroiu** [comment]
Confirmation screen after activation redesign

**Comment by RaduAlbastroiu** [comment]
Modal for create new tweet and post it
